# Generated by Django 3.1.13 on 2021-12-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0002_imageitem_imagemodel'),
        ('example_app', '0003_remove_mmimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmexample',
            name='images',
            field=models.ManyToManyField(blank=True, to='django_base.ImageModel'),
        ),
        migrations.DeleteModel(
            name='ImageItem',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
