# Generated by Django 3.1.13 on 2021-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_add_field_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexamplemodel',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
