# Generated by Django 3.1.13 on 2021-12-03 13:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0004_add_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='example',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalexamplemodel',
            name='example',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
